server:
  port: 8080

spring:
  datasource:
    name: OA
    url: jdbc:mysql://104.207.142.224:3306/OA?zeroDateTimeBehavior=convertToNull
    username: team
    password: Team@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.thzw.thethzw.entity

spring.mvc.static-path-pattern: /static/**